spring:
  application:
    name: firverse-activity-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/firverse_activity
      database: firverse_activity
server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/